// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TopScoreApi.Infrastructure.Persistence.DataAccess;

#nullable disable

namespace TopScoreApi.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261007203718_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("TopScoreApi.Domain.Entities.TestScore", b =>
                {
                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("FirstName", "LastName");

                    b.ToTable("TestScores", t =>
                        {
                            t.HasCheckConstraint("CK_TestScore_FirstName_NotEmpty", "length(FirstName) > 0");

                            t.HasCheckConstraint("CK_TestScore_LastName_NotEmpty", "length(LastName) > 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
